"""make_resume_github_username_nullable

Revision ID: 2ed0e19c9743
Revises: 9e90628545e6
Create Date: 2026-03-22 19:32:04.470208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed0e19c9743'
down_revision: Union[str, None] = '9e90628545e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'github_username',
               existing_type=sa.VARCHAR(length=39),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'github_username',
               existing_type=sa.VARCHAR(length=39),
               nullable=False)
    # ### end Alembic commands ###
