"""initial tables

Revision ID: e16eea39801b
Revises: 
Create Date: 2026-03-22 17:43:19.930375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e16eea39801b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_username', sa.String(length=39), nullable=False),
    sa.Column('analysis_date', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('public_repos', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('account_age_days', sa.Integer(), nullable=True),
    sa.Column('score_overall', sa.Float(), nullable=False),
    sa.Column('score_project_diversity', sa.Float(), nullable=False),
    sa.Column('score_language_breadth', sa.Float(), nullable=False),
    sa.Column('score_commit_consistency', sa.Float(), nullable=False),
    sa.Column('score_readme_quality', sa.Float(), nullable=False),
    sa.Column('score_community_engagement', sa.Float(), nullable=False),
    sa.Column('score_originality', sa.Float(), nullable=False),
    sa.Column('top_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_repos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_feedback', sa.Text(), nullable=True),
    sa.Column('llm_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_username', 'analysis_date', name='uq_username_day')
    )
    op.create_index('ix_analyses_username', 'github_analyses', ['github_username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('github_username', sa.String(length=39), nullable=True),
    sa.Column('auth_provider', sa.String(length=10), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_sub_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider', 'provider_id', name='uq_provider'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['github_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'analysis_id', name='uq_user_analysis')
    )
    op.create_index(op.f('ix_user_analyses_user_id'), 'user_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_analyses_user_id'), table_name='user_analyses')
    op.drop_table('user_analyses')
    op.drop_table('users')
    op.drop_index('ix_analyses_username', table_name='github_analyses')
    op.drop_table('github_analyses')
    # ### end Alembic commands ###
